### ISSUE TITLE
Name of package and private vs. public

### ISSUE THREAD

**Issue by kthyng** [NOAA-ORR-ERD/model_catalogs#1]
@ChrisBarker-NOAA I see you named this differently than I have thus far named `model_catalogs`. I have a preference for keeping it the way I have it (lowercase with underscore), which [fits with Python convention](https://peps.python.org/pep-0008/#package-and-module-names) but what do you think? cc @lukecampbell @AmyMacFadyen @jay-hennen 

Also I see this repo is private — do you want to go public with it like you did with LibGOODS?

**Comment by ChrisBarker-NOAA** [comment]
Done. though I was too fast, and I used the underscore.

Honestly, I"m am very, very confused as to why the packaging community thinks that the hyphen should be the "normalized" package name -- why would you want an illegal python name as the package name???

So I tend to use the underscore as a form of resistance ;-)

But your call.

**Comment by kthyng** [comment]
Let's take this as it is. I had it this way anyway. Thank you!
