### ISSUE TITLE
RTOFS sources

### ISSUE THREAD

**Issue by kthyng** [NOAA-ORR-ERD/model_catalogs#30]
RTOFS sources are working from NOMADS again, but they are a bit odd. I currently have a "forecast" and "nowcast" for them but 
the difference between forecast and nowcast depends on the RTOFS model but is usually one is based on "today" and one is based on "yesterday" and I didn't see a better way to combine the files together than what I have in the catalog file to make a comprehensive time series. (Usually yesterday is used in "forecast" because otherwise you might get caught by the fact the files aren't actually available yet if I used today instead.)

Are they agg or no agg? They aren't technically aggregated, but also no logic is required to put them together since there are only a few files and their form is listed in the catalog. 

How would you like me to handle RTOFS?

**Comment by AmyMacFadyen** [comment]
Its been awhile since I looked at this. If I recall correctly, they have two output directories (yesterday and today). They both contain nowcast and forecast files. Are you aggregating the nowcast and forecast together or are they separate "sources"?

**Comment by kthyng** [comment]
RTOFS "forecasts" use yesterday's directory to make sure it is available. They contain urlpaths of the nowcast and the forecast so they would be both read in. They extend in time from 2 days ago through 5 days from now (at least for Alaska). For example,

https://github.com/NOAA-ORR-ERD/model_catalogs/blob/7940b86d5e3cc3bcd87b042c6016aad23e57f008/model_catalogs/catalogs/orig/rtofs-alaska.yaml#L32-L34

RTOFS "nowcasts" use today's directory and so don't work for the first part of the day before the simulations are run. They extend in time from yesterday through 5 days from now.

The global RTOFS sources do map in model_catalogs by nowcast and forecast separately and instead list the different variables available, for example:

https://github.com/NOAA-ORR-ERD/model_catalogs/blob/7940b86d5e3cc3bcd87b042c6016aad23e57f008/model_catalogs/catalogs/orig/rtofs-global-2d.yaml#L28-L31

**Comment by kthyng** [comment]
Closing this in favor of https://github.com/NOAA-ORR-ERD/model_catalogs/issues/31
