### ISSUE TITLE
Changing names of "timings" to "sources"

### ISSUE THREAD

**Issue by kthyng** [NOAA-ORR-ERD/model_catalogs#31]
Here is my summary of our discussion about changing "timings" to "sources" to see if everyone agrees on the plan:

* use "source" in place of "timing" everywhere
* see list for specific name changes. I included a couple of possible future sources to imagine what they could be called.
* the convention is `catalog name`: `source name`

Was | Proposal
-- | -- 
CIOFS: forecast | CIOFS: coops-forecast-agg 
CIOFS: nowcast | CIOFS: coops-forecast-noagg 
CIOFS: hindcast | CIOFS: ncei-archive-noagg 
CIOFS: hindcast-forecast-aggregation | CIOFS: ncei-archive-agg 
CIOFS-REGULARGRID: forecast | CIOFS-REGULARGRID: coops-forecast-noagg 
GOMOFS-2DS: forecast | GOMOFS-2DS: coops-forecast-noagg 
GOMOFS-2DS: hindcast | GOMOFS-2DS: ncei-archive-noagg 
CBOFS: new IOOS source | CBOFS: ioos-forecast-agg 
CIOFS: future AWS source | CIOFS: aws-forecast-noagg 
HYCOM: forecast | HYCOM: hycom-forecast-agg 
GFS-1DEG: forecast | GFS-1DEG: ucar-forecast-agg 
RTOFS-GLOBAL: forecast | RTOFS-GLOBAL: nomads-forecast-? 
RTOFS-GLOBAL: nowcast | RTOFS-GLOBAL: nomads-forecast-?

Let's discuss RTOFS specifically in https://github.com/NOAA-ORR-ERD/model_catalogs/issues/30.

@ChrisBarker-NOAA @AmyMacFadyen @jay-hennen

**Comment by ChrisBarker-NOAA** [comment]
LGTM.

Note: I did write a note somewhere that I can't seem to find about the top-level naming (i.e. not the source issue). Ideally we'd have three things:

1) An ID -- short and sweet, e.g. CBOFS
2) A name -- moderate length: e.g. Chea=sapeake Bay Operational Forecast Model
3) A description: the full description

I think we current have (1) and (3), but not (2) -- I think that would be helpful.

Otherwise, we could establish the convention that the first line of the description be a long name -- that might be easier than metadata.

Other Note: IDs can ans should be short, e.g., maybe:

CIOFS-RGRID (or even CBOFS-R )rather than CIOFS-REGULARGRID

and HYCOM should probably be GOFS or GFS3.1 -- or at least GLOBAL-HYCOM or USN-HYCOM

**Comment by AmyMacFadyen** [comment]
I actually started adding this to model catalogs awhile ago but haven't committed anything. Initially, I changed the "name" field in the yaml file to be the longer name (e.g. Chesapeake Bay) and added an ID. But this broke a bunch of things the way the catalogs were structured before (i.e. writing the extra metadata files to another catalog). 

If that's no longer the case, I'd prefer that option (i.e. ID=CBOFS, name=Chesapeake Bay, description='NOAA COOPS OFS..') However, if renaming "name" to "id" is problematic, I'd also be fine with name=CBOFS, long_name=Chesapeake Bay, description='NOAA COOPS OFS..'

Kristen, I am happy to contribute to this "busywork" because its important mainly to what we're displaying in the WebGNOME client. But I wanted to get your advice on which way to go first.

**Comment by kthyng** [comment]
Intake has a [few attributes built in](https://intake.readthedocs.io/en/latest/catalog.html#sources). `name` is the identifier for Intake and if we add other attributes, they wouldn't be known to Intake so wouldn't be propagated when saved, etc. However, the metadata is always propagated.

So, my suggestion would be, following Amy's suggestion:

1. Keep name=CBOFS
2. add `long_name` under metadata (see note below)
3. Keep description as is


Note that generally the rules are the same for the Catalog as they are for the Source. To be clear, the Catalog-level info is:

https://github.com/NOAA-ORR-ERD/model_catalogs/blob/3b11aced001a67df5664c583a57f5be35e0383e7/model_catalogs/catalogs/orig/cbofs.yaml#L1-L9

and an example Source level is:

https://github.com/NOAA-ORR-ERD/model_catalogs/blob/3b11aced001a67df5664c583a57f5be35e0383e7/model_catalogs/catalogs/orig/cbofs.yaml#L12-L41

An implication of this is that you should decide if you want your `long_name` in the Catalog metadata at the top of the file (applying to all the sources in the Catalog) or if you want it in each Source.

**Comment by AmyMacFadyen** [comment]
Thanks, Kristen. I am good with adding a long_name to the metadata at the Catalog level.

I can do this if you like. 

From our perspective the long_name would be what would appear in the model selection list in WebGNOME - so it would just be a logical name for the region covered and maybe the provider, e.g Chesapeake Bay Model (NOAA), West Coast US (NOAA), Global (NAVO)...it may take some iteration for agreement, so it might be easiest for us to handle it :)

**Comment by kthyng** [comment]
I'll leave this to you!

**Comment by kthyng** [comment]
Ok here are my updated proposals. I have changed 2 in this first table. 

Was | Updated Proposal
-- | --
CIOFS: forecast | CIOFS: coops-forecast-agg
CIOFS: nowcast | CIOFS: coops-forecast-noagg
CIOFS: hindcast | CIOFS: ncei-archive-noagg
CIOFS: hindcast-forecast-aggregation | CIOFS: ncei-archive-agg
CIOFS-REGULARGRID: forecast | CIOFS-RGRID*: coops-forecast-noagg
GOMOFS-2DS: forecast | GOMOFS-2DS: coops-forecast-noagg
GOMOFS-2DS: hindcast | GOMOFS-2DS: ncei-archive-noagg
CBOFS: new IOOS source | CBOFS: ioos-forecast-agg
CIOFS: future AWS source | CIOFS: aws-forecast-noagg
HYCOM: forecast | GOFS*: hycom-forecast-agg
GFS-1DEG: forecast | GFS-1DEG: ucar-forecast-agg


The second table spells out all of RTOFS to try to get feedback. I pulled together nowcast and forecast files to make time series for two sources for each model type. The model file paths are specified in the catalog file (based on either today or yesterday's date) so none of the `model_catalogs` code to deal with unaggregated NOAA OFS models applies. However, they are not opendap-based preaggregated models. So, do they count as unaggregated or aggregated? Do you want to save both source for each model that I have listed in the table? If so, how would you like to name them when they start today vs. yesterday? Note that the files based on today's date are typically not available until mid-morning to mid-day on a given day, so they are not reliable at any given moment, which is why I put the results from "yesterday" as being the "forecast" to make sure they'll always be available. 

Please add your feedback so I can move forward on all these decisions, and let me know if you have questions.

Was | Updated Proposal
-- | --
RTOFS-GLOBAL: forecast | RTOFS: nomads-forecast-? (daily yesterday through 7 days from today) 
RTOFS-GLOBAL: nowcast | RTOFS: nomads-forecast-? (daily today through 8 days from today)
RTOFS-GLOBAL-2D: forecast | RTOFS-2D: nomads-forecast-3hourly-? (yesterday 3 hourly through 6 days)
RTOFS-GLOBAL-2D: forecast2 | RTOFS-2D: nomads-forecast-3hourly-? (today 3 hourly through 7 days, this one is new)
RTOFS-GLOBAL-2D: nowcast | RTOFS-2D: nomads-forecast-hourly (2 days ago hourly through yesterday)
RTOFS-ALASKA: forecast | RTOFS-AK: nomads-forecast-? (2 days ago to 4 days from now, 6 hourly)
RTOFS-ALASKA: nowcast | RTOFS-AK: nomads-forecast-? (yesterday to 5 days from now, 6 hourly)
RTOFS-WEST: forecast | RTOFS-WEST: nomads-forecast-? (Similar setup to others but currently forecast is EAST file)
RTOFS-WEST: nowcast | RTOFS-WEST: nomads-forecast-? (Similar setup to others but currently forecast is EAST file)
RTOFS-EAST: forecast | RTOFS-EAST: nomads-forecast-? (2 days ago to 4 days from now, 6 hourly)
RTOFS-EAST: nowcast | RTOFS-EAST: nomads-forecast-? (yesterday to 5 days from now, 6 hourly)

**Comment by kthyng** [comment]
@AmyMacFadyen Gave input elsewhere so the RTOFS plan is:

Was | Updated Proposal
-- | --
RTOFS-GLOBAL: forecast | RTOFS: nomads-forecast-yesterday (daily yesterday through 7 days from today) 
RTOFS-GLOBAL: nowcast | RTOFS: nomads-forecast-today (daily today through 8 days from today)
RTOFS-GLOBAL-2D: forecast | RTOFS-2D: nomads-forecast-yesterday (yesterday 3 hourly through 6 days)
RTOFS-GLOBAL-2D: forecast2 | RTOFS-2D: nomads-forecast-today (today 3 hourly through 7 days, this one is new)
RTOFS-GLOBAL-2D: nowcast | RTOFS-2D: nomads-archive-hourly (2 days ago hourly through yesterday)
RTOFS-ALASKA: forecast | RTOFS-AK: nomads-forecast-yesterday (2 days ago to 4 days from now, 6 hourly)
RTOFS-ALASKA: nowcast | RTOFS-AK: nomads-forecast-today (yesterday to 5 days from now, 6 hourly)
RTOFS-WEST: forecast | RTOFS-WEST: nomads-forecast-yesterday (Similar setup to others but currently forecast is EAST file)
RTOFS-WEST: nowcast | RTOFS-WEST: nomads-forecast-today (Similar setup to others but currently forecast is EAST file)
RTOFS-EAST: forecast | RTOFS-EAST: nomads-forecast-yesterday (2 days ago to 4 days from now, 6 hourly)
RTOFS-EAST: nowcast | RTOFS-EAST: nomads-forecast-today (yesterday to 5 days from now, 6 hourly)

**Comment by AmyMacFadyen** [comment]
@kthyng Will we need to specify a "default" source for each model? I notice in some places we in model_catalogs you have to choose a source (e.g. generating the boundary) and you used the forecast (if available). For the boundary, it doesn't really matter which you choose but I'm curious how you will handle this. It might not be a bad idea to specify the "preferred" access method in the main metadata? Since all the source names will now be more specific.

**Comment by kthyng** [comment]
@AmyMacFadyen I was thinking of just choosing the first source in the model file, or the first that works at the moment it is being requested at least, since you are right in some cases it doesn't matter which is used. What do you think?

**Comment by AmyMacFadyen** [comment]
That seems fine to me. If I add a more "preferred" access method for any of them, I'll be sure to put it first :)

**Comment by AmyMacFadyen** [comment]
@kthyng One last note on this -- what's your preference for the renaming of "timings".  It sounds like we agree that "source" is already an overloaded term. Do you prefer "model_source", "source_name", "model_access"? -- I can't think of anything good but to me its basically the "where" and "how" we are retrieving the results...

**Comment by kthyng** [comment]
@AmyMacFadyen My reasoning for "source_name" is that the object being referred to in that case is an intake Source, so the string identifying it could the be "source_name". Now that I think about it, I use "model" to refer to the name of the intake Catalog – instead of "cat_name" – so that isn't consistent across the two. Maybe "model_source" would be more consistent with using "model" in that case. Would you prefer "model_source"?

**Comment by kthyng** [comment]
Work done in https://github.com/NOAA-ORR-ERD/model_catalogs/pull/47
