### ISSUE TITLE
Set up for code coverage analysis

### ISSUE THREAD

**Issue by kthyng** [NOAA-ORR-ERD/model_catalogs#5]
@ChrisBarker-NOAA Can I go through the steps to set up code coverage on this repo? Here is the quick start link: https://docs.codecov.com/docs It looks like I have enough permissions to set it up, but I wanted to make sure you're ok with that before I do so.

**Comment by kthyng** [comment]
I think this actually is working now! The downside is that a lot of the testing happens locally because it is slow, so that isn't captured in the code coverage statistic. But it is running now.

**Comment by ChrisBarker-NOAA** [comment]
cool!

maybe we could have the complete test suite run once in a while -- oor maybe only on the main branch?

but I'm happy for developers to run coverage locally anyway.

**Comment by kthyng** [comment]
Yes good point — I'll see how to run the slow tests with maybe just one test environment.
